services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      target: dev
    ports:
      - '8443:4343'
    depends_on:
      mvc:
        condition: service_healthy
    networks:
      - lan
  api:
    build: 
      context: ./API
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./API:/app
    hostname: api
    ports:
      - '4343:4343'
      - '9320:9320'
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-Ifk", "https://localhost:4343/docs/json"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lan

  mvc:
    build:
      context: ./MVC
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./MVC:/app
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-Ifk", "https://localhost:4343/"]
      interval: 10s
      timeout: 5s
      retries: 5
    hostname: ponggame
    ports:
      - "8000:4343"
      - '9321:9320'
    depends_on:
      api:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - lan
  
  minio:
    build:
      context: ./minio
      dockerfile: Dockerfile
      target: dev
    volumes:
      - "./minio/data:/data"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-Ifk", "https://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - lan

networks:
  lan:
    driver: bridge