services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      target: dev
    ports:
      - '443:4343'
    depends_on:
      - mvc
  api:
    build: 
      context: ./API
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./API:/app
    ports:
      - '3000:3000'
    env_file:
      - .env

  mvc:
    build:
      context: ./MVC
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./MVC:/app
    env_file:
      - .env
    hostname: ponggame
    depends_on:
      - api

networks:
  lan:
    driver: bridge