global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fastify-api'
  static_configs:
    - targets: ['api:4343']
  metrics_path: '/api/v1/metrics'
  scrape_interval: 10s
  scheme: https
  tls_config:
    insecure_skip_verify: true

  - job_name: 'prometheus'
  static_configs:
    - targets:: ['localhost:9090']
